### ISSUE TITLE
Repurposing

### ISSUE THREAD

**Issue by ejmlife** [KronosDesign/MultiInstanceManager#1]
Hi,
I'm currently trying to get this working on a different version of runelite (Zenyte RSPS) but im a bit of a noob at coding. I've been trying to find where it tells which windows to inculde in the manager buit had no luck. I know this is an old project but if you could shed any light i'd be very appreciative.

Cheers

**Comment by KronosDesign** [comment]
You should be able to change this line to match the window title of your client:
https://github.com/KronosDesign/MultiInstanceManager/blob/master/MultiInstanceManager/MainWindow.xaml.cs#L104

You'll most likely need to modify the window styles to match also:
https://github.com/KronosDesign/MultiInstanceManager/blob/master/MultiInstanceManager/MainWindow.xaml.cs#L47-L49
You can check your window style by using Spy++ from the VS tools menu.
